# Generated by Django 4.2.13 on 2024-06-07 03:01

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Chọn nếu cho phép người dùng hoạt động')),
                ('is_verify', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, help_text='Kích thước 300x300px', null=True, upload_to=customer.models.get_upload_to)),
            ],
            options={
                'db_table': 'bs_customers',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email',), name='uq_customers_email'),
        ),
    ]
