# Generated by Django 4.2.13 on 2024-06-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_note_alter_order_required_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_amount',
        ),
    ]
