# Generated by Django 4.2.13 on 2024-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
