# Generated by Django 5.0.1 on 2024-02-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Old'), (3, 'Refurbished')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chấp nhận giá trị từ 0 - 70 (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Chọn nếu sản phẩm đang bán'),
        ),
    ]
