# Generated by Django 5.0.1 on 2024-02-27 04:51

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, help_text='Kích thước 400x400px', null=True, upload_to=product.models.get_upload_to),
        ),
    ]
