# Generated by Django 4.2.13 on 2024-06-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_description_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, default=None, help_text='Nên nằm trong khoảng 155-160 kí tự', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default=None, help_text='Nên nằm trong khoảng 55-70 kí tự', max_length=255, null=True),
        ),
    ]
