# Generated by Django 5.0.1 on 2024-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'bs_brands',
                'ordering': ['brand_name'],
            },
        ),
    ]
