# Generated by Django 5.0.1 on 2024-02-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_active_brand_created_at_brand_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='active',
            new_name='is_active',
        ),
    ]
