# Generated by Django 5.0.1 on 2024-02-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_rename_active_brand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
