# Generated by Django 5.0.1 on 2024-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
