# Generated by Django 5.0.1 on 2024-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='bs_categories',
        ),
    ]
