# Generated by Django 5.0.1 on 2024-02-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_active_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='is_active',
        ),
    ]
