# Generated by Django 5.0.1 on 2024-02-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_active_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
